{
 "title": "Qpid Dispatch Router",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Deliveries ingress",
   "type": "graph",
   "description": "Number of deliveries that were sent to the router by a sender that is directly attached to the router.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(qdr_deliveries_ingress_total)",
     "legendFormat": "Deliveries ingress"
    }
   ]
  },
  {
   "title": "Deliveries egress",
   "type": "graph",
   "description": "Number of deliveries that were sent by the router to a receiver that is directly attached to the router.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(qdr_deliveries_egress_total{job='qdmetrics'})",
     "legendFormat": "Deliveries egress"
    }
   ]
  },
  {
   "title": "Auto links",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(qdr_auto_links_total{job='qdmetrics'})",
     "legendFormat": "Autolinks"
    }
   ]
  },
  {
   "title": "Deliveries ingress route container",
   "type": "graph",
   "description": "Number of deliveries that were received from router container connections.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "qdr_deliveries_ingress_route_container_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Deliveries egress route container",
   "type": "graph",
   "description": "Number of deliveries that were sent to route container connections.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "qdr_deliveries_egress_route_container_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Link routes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(qdr_link_routes_total{job='qdmetrics'})",
     "legendFormat": "Link routes"
    }
   ]
  },
  {
   "title": "Deliveries redirected to fallback destination",
   "type": "graph",
   "description": "Number of deliveries that were sent to the fallback destination due to the primary destination being unreachable.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "qdr_deliveries_redirected_to_fallback_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Dropped presettled deliveries",
   "type": "graph",
   "description": "Number of presettled deliveries that were dropped by the router.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "qdr_dropped_presettled_deliveries_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Presettled deliveries",
   "type": "graph",
   "description": "Number of presettled deliveries handled by the router.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "qdr_presettled_deliveries_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Address Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(qdr_addresses_total{job='qdmetrics'})",
     "legendFormat": "Address count"
    }
   ]
  },
  {
   "title": "Connection count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(qdr_connections_total)", "legendFormat": "Connection count" }
   ]
  },
  {
   "title": "Link count",
   "type": "graph",
   "description": "Number of links attached to the router node.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(qdr_links_total)", "legendFormat": "Link count" }
   ]
  }
 ]
}