{
 "title": "Qpid Dispatch Router - Delayed deliveries",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Cumulative delayed 10 seconds",
   "type": "graph",
   "description": "Total number deliveries delayed for 10 or more since the router was started",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "qdr_deliveries_delayed_10sec_total",
     "legendFormat": "10s {{instance}}"
    }
   ]
  },
  {
   "title": "Cumulative delayed 1 second",
   "type": "graph",
   "description": "Total number deliveries delayed for 1 or more since the router was started",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "qdr_deliveries_delayed_1sec_total",
     "legendFormat": "1s {{instance}}"
    }
   ]
  },
  {
   "title": "Rate of new delayed deliveries",
   "type": "graph",
   "description": "The rate delayed deliveries is increasing for the last minute",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(qdr_deliveries_delayed_10sec_total[1m])",
     "legendFormat": "10s {{instance}}"
    },
    {
     "expr": "rate(qdr_deliveries_delayed_1sec_total[1m])",
     "legendFormat": "1s {{instance}}"
    }
   ]
  }
 ]
}